### ISSUE TITLE
"With Black" should show Black text

### ISSUE THREAD

**Issue by jhogue** [oomphinc/colorcube#3]
With white makes sense, because you can see the contrast issues as the white text is over the color. But with black, we should change the default text color to be black in this case, so you can also see the visual implications of non accessible color combinations.

**Comment by syzygy333** [comment]
PR for this here: https://github.com/oomphinc/colorcube/pull/5

**Comment by balbuf** [comment]
Why would you want to do this? This makes ratios sometimes hard to read: proving a point, I suppose, but I feel like the app should follow its own advice when conveying key information. Seems like it would be more beneficial to show example text on the user-provided color in both white and black for demonstration purposes, and leave the proper contrast for the "ratio score" colors.

**Comment by jhogue** [comment]
There are going to be some colors where neither black nor white are legible over the color. The contrast ratio as well, is meant to ensure that two colors with similar saturation and brightness can still be distinguished from one another, even though the person may have not be able to perceive hue. 

Our users will most likely not be color blind, but they could be, so I take your point. Our intent was to show as much information as possible for each color in the list. Other tools only look at one color at a time, or give you one contrast ratio at a time. We wanted to give a user a useful table of information to help make informed decisions about color. 

Seems like we need a better long range plan for the tool and the interface. One which achieves the goal but also adheres to its own guidelines for contrast.

**Comment by balbuf** [comment]
Yeah but you're talking about known colors here: green, red, yellow. Right? The user didn't come to get a demo on whether black or white is legible over green, red, and yellow - they want to know what it looks like with _their_ colors.
