### ISSUE TITLE
Add a small version of the ratio to indicate small text

### ISSUE THREAD

**Issue by jhogue** [oomphinc/colorcube#4]
I think that instead of giving the user text radio buttons to switch between small text and large, that we provide as much information as possible for each color at a glance. 

I propose smaller squares to indicate small text vs. large text. And follow it up with an explanation, maybe even a visual key of some sort. Something like this: 

![colorcube-improvements](https://cloud.githubusercontent.com/assets/1530232/26376362/371dd3b6-3fda-11e7-9387-66917175ce66.jpg)

We might have to refactor the JS a little to allow for different WCAG values, as well as structure the columns differently, but i think it can be achieved fairly easily.

**Comment by syzygy333** [comment]
I'll work on this.

**Comment by syzygy333** [comment]
Submitted PR for this here: https://github.com/oomphinc/colorcube/pull/9
Doesn't include styling as those changes are still under consideration

**Comment by jhogue** [comment]
Changed on the new UI. Closed for lack of relevance.
