### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by mgifford** [oomphinc/colorcube#42]
I think you've set this up to support dark mode, but haven't said explicitly how to test for dark mode support. 

Being able to provide good support for accessibility in light/dark mode isn't simple.

**Comment by jhogue** [comment]
Hello @mgifford. Dark mode was added upon merging of an interface refactor (PR #41). Current OS setting is detected and came be overridden in the "Settings" tab. 

I will create new issue for a small "reset" enhancement, which would remove the cookie (if the user has made a selection) and go back to System setting preference.
