### ISSUE TITLE
Add a legal notice/disclaimer

### ISSUE THREAD

**Issue by syzygy333** [oomphinc/colorcube#8]
Let the user know something to the effect of "This tool is for general assessment purposes only and not a guarantee of compliance."

**Comment by jhogue** [comment]
From http://www.ssbbartgroup.com/reference/color-contrast-checker/, I like: 

The algorithm used in this tool and subsequent results are based on the luminosity algorithm recommended in the WCAG 2.0 guidelines to test for contrast. This tool is for general assessment purposes only and not a guarantee of compliance.

**Comment by jhogue** [comment]
Added in a previous (old) commit.
